version: "1.0"

# WHO: LintingSystem
# WHAT: GoLangCI-Lint Configuration
# WHEN: During code analysis
# WHERE: GitHub MCP Server
# WHY: To enforce Go code quality standards
# HOW: Using a minimal linter configuration
# EXTENT: All Go code in the MCP server

# Core linting configuration
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - revive
    - ineffassign
    - unused
    - gosimple
    - misspell
    - nakedret
    - bodyclose
    - gocritic
    - gosec

# Run configuration
run:
  timeout: 5m
  tests: true
  concurrency: 4
  
# Issues management
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
