# WHO: GoReleaser Workflow (GitHub MCP Server)
# WHAT: GitHub Actions workflow for GoReleaser
# WHEN: On tag push (v*)
# WHERE: .github/workflows/goreleaser.yml (GitHub MCP Server)
# WHY: To automate GoReleaser builds and provenance
# HOW: Standard GitHub Actions YAML structure
# EXTENT: Full release pipeline

name: GoReleaser Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate signed build provenance attestations for workflow artifacts
        uses: actions/attest-build-provenance@v2
